{
 "title": "CPU Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overall CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[10s])) * 100)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Per CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance, cpu) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[10s])) * 100)"
    }
   ]
  },
  {
   "title": "Frequency Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz / 100000"
    }
   ]
  }
 ]
}